#!/usr/bin/env python3
"""Install GPU-enabled KataGo assets suitable for Linux."""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
import tempfile
import urllib.request
import zipfile
from pathlib import Path


KATAGO_RELEASE = "v1.16.3"
KATAGO_ARCHIVES = [
    ("katago-v1.16.3-cuda12.1-cudnn8.9.7-linux-x64.zip", "f09b952ebca7a72d243a211d9d16a58d65d57515091ec95692f7ebe74e252ec4"),
    ("katago-v1.16.3-cuda-linux-x64.zip", None),
]
MODEL_NAME = "kata1-b28c512nbt-s11084575488-d5365903487.bin.gz"
def katago_url(archive_name: str) -> str:
    return f"https://github.com/lightvector/KataGo/releases/download/{KATAGO_RELEASE}/{archive_name}"
MODEL_URL = f"https://media.katagotraining.org/uploaded/networks/models/kata1/{MODEL_NAME}"


DEFAULT_CFG = """# Auto-generated by scripts/install_katago.py
logSearchInfo = false
ponderingEnabled = false
kataGoServer = false
maxVisits = 800
maxPlayouts = 0
numSearchThreads = 8
analysisWideRootNoise = 0.0
lagBufferWindow = 0
resignThreshold = -0.999
resignConsecTurns = 3
resignMinScoreDifference = 1.0
resignScoreProbability = 1.0
modelFile = {model_rel}
rules = tromp-taylor
allowResignation = true
allowSelfHandicap = false
dynamicPlayoutDoublingAdvantageCapPerOppLead = 0.0
playoutDoublingAdvantageCapPerOppLead = 0.0
inputRandomness = 0
cudaUseFP16 = true
cudaUseNHWC = true
cudaGraphMaxBatchSize = 0
cudaGraphWorkspaceMB = 128
allowMultipleInputModes = false
useFastForcedRootMove = true
useTreeHash = false
defaultBoardSize = 19
handicap = false
avoidMoveUntilByRevMove = false
"""


class InstallError(RuntimeError):
    pass


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def katago_dir() -> Path:
    return repo_root() / "katago"


def archives_dir() -> Path:
    return repo_root() / "katago_archives"


def download(url: str, dest: Path, sha256: str | None = None) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(dest.suffix + ".tmp")
    if tmp.exists():
        try:
            tmp.unlink()
        except PermissionError:
            tmp = dest.with_suffix(dest.suffix + ".tmp2")

    print(f"[download] {url}\n           -> {dest}")
    try:
        with urllib.request.urlopen(url) as response, tmp.open("wb") as fh:
            shutil.copyfileobj(response, fh)
    except Exception as exc:
        raise InstallError(f"Failed to download {url}: {exc}") from exc

    if sha256:
        digest = hashlib.sha256(tmp.read_bytes()).hexdigest()
        if digest.lower() != sha256.lower():
            tmp.unlink(missing_ok=True)
            raise InstallError(f"SHA256 mismatch for {dest.name}")

    tmp.replace(dest)


def ensure_archive(force: bool, search_dirs: list[Path]) -> Path:
    for archive_name, _ in KATAGO_ARCHIVES:
        for directory in search_dirs:
            candidate = directory / archive_name
            if candidate.is_file() and not force:
                print(f"[cache] Using existing archive: {candidate}")
                return candidate

    errors: list[str] = []
    for archive_name, sha256 in KATAGO_ARCHIVES:
        cache_path = archives_dir() / archive_name
        try:
            download(katago_url(archive_name), cache_path, sha256=sha256)
            return cache_path
        except InstallError as exc:
            errors.append(f"{archive_name}: {exc}")
            try:
                cache_path.unlink()
            except FileNotFoundError:
                pass

    details = "\n".join(errors) if errors else "no archives attempted"
    raise InstallError(f"Failed to download KataGo archive:\n{details}")


def extract_katago(archive: Path, target: Path) -> None:
    print(f"[extract] {archive} -> {target}")
    with zipfile.ZipFile(archive) as zf, tempfile.TemporaryDirectory() as tmpdir:
        zf.extractall(tmpdir)
        temp_root = Path(tmpdir)
        binary_candidates = list(temp_root.rglob("katago"))
        if not binary_candidates:
            raise InstallError("KataGo binary not found in archive")
        binary_candidates.sort(key=lambda p: len(p.parts))
        target.mkdir(parents=True, exist_ok=True)
        shutil.copy2(binary_candidates[0], target / "katago")
        (target / "katago").chmod(0o755)
        example_cfg = list(temp_root.rglob("gtp_example.cfg"))
        if example_cfg and not (target / "default_gtp.cfg").exists():
            shutil.copy2(example_cfg[0], target / "default_gtp.cfg")


def ensure_model(force: bool, target: Path) -> str:
    model_path = target / MODEL_NAME
    tmp_path = model_path.with_suffix(model_path.suffix + ".tmp")
    tmp2_path = model_path.with_suffix(model_path.suffix + ".tmp2")

    for leftover in (tmp_path, tmp2_path):
        if leftover.exists():
            try:
                leftover.unlink()
            except PermissionError:
                pass

    if model_path.exists():
        if force:
            try:
                model_path.unlink()
            except PermissionError:
                pass
        else:
            print(f"[skip] model already exists: {model_path}")
            return MODEL_NAME

    download(MODEL_URL, model_path)
    return MODEL_NAME


def write_default_cfg(target: Path, model_filename: str) -> None:
    cfg_path = target / "default_gtp.cfg"
    cfg_text = DEFAULT_CFG.format(model_rel=model_filename)
    cfg_path.write_text(cfg_text, encoding="utf-8")
    print(f"[write] default_gtp.cfg -> {cfg_path}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Download KataGo GPU build for Linux")
    parser.add_argument("--archive-dir", action="append", default=[], help="Additional cache directory")
    parser.add_argument("--force", action="store_true", help="Redownload and overwrite existing files")
    parser.add_argument("--env-name", default=None, help="Unused placeholder for compatibility")
    args = parser.parse_args(argv)

    target_dir = katago_dir()
    if args.force and target_dir.exists():
        print(f"[cleanup] removing {target_dir}")
        shutil.rmtree(target_dir, ignore_errors=True)
    target_dir.mkdir(parents=True, exist_ok=True)

    extra_dirs = [Path(p).expanduser() for p in args.archive_dir]
    for d in extra_dirs:
        d.mkdir(parents=True, exist_ok=True)

        archive = ensure_archive(force=args.force, search_dirs=extra_dirs + [archives_dir()])
    extract_katago(archive, target_dir)
    model_filename = ensure_model(force=args.force, target=target_dir)
    write_default_cfg(target_dir, model_filename)

    print("[done] KataGo GPU installation complete")
    print(f"       Binary: {target_dir / 'katago'}")
    print(f"       Model:  {target_dir / model_filename}")
    print(f"       Config: {target_dir / 'default_gtp.cfg'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())


